// @ts-expect-error -- ts can't find types for eslint-config-next
import nextTypescript from "eslint-config-next/typescript";
import { defineConfig } from "eslint/config";
// @ts-expect-error -- ts can't find types for eslint-config-next
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import path from "node:path";
import { fileURLToPath } from "node:url";
import js from "@eslint/js";
import { FlatCompat } from "@eslint/eslintrc";

const filename = fileURLToPath(import.meta.url);
const dirname = path.dirname(filename);
const compat = new FlatCompat({
  baseDirectory: dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

const eslintConfig = defineConfig([
  ...nextTypescript,
  { ignores: ["node_modules", "dist", "build", ".next", "out", "public/data"] },
  {
    extends: [...nextCoreWebVitals, ...compat.extends("eslint:recommended")],

    rules: {
      "accessor-pairs": 2,
      "array-bracket-newline": 0,
      "array-bracket-spacing": [2, "never"],
      "array-callback-return": 2,
      "array-element-newline": 0,
      "arrow-body-style": 0,
      "arrow-parens": 2,
      "arrow-spacing": 2,
      "block-scoped-var": 2,
      "block-spacing": 2,
      "brace-style": [1, "1tbs"],
      "callback-return": 2,
      camelcase: 0,
      "capitalized-comments": 0,
      "class-methods-use-this": 2,
      "comma-dangle": [0, "never"],
      "comma-spacing": 2,
      "comma-style": [2, "last"],
      complexity: [0, 11],
      "computed-property-spacing": [2, "never"],
      "consistent-return": 2,
      "consistent-this": [2, "that"],
      "constructor-super": 2,
      curly: [2, "all"],
      "default-case": 2,
      "default-case-last": 2,
      "default-param-last": 2,
      "dot-location": 0,

      "dot-notation": [
        0,
        {
          allowKeywords: true,
        },
      ],

      "eol-last": 2,
      eqeqeq: 2,
      "for-direction": 2,
      "func-call-spacing": 2,
      "func-name-matching": 2,
      "func-names": 0,
      "func-style": [0, "declaration"],
      "function-call-argument-newline": 0,
      "function-paren-newline": 0,
      "generator-star-spacing": 2,
      "getter-return": 2,
      "global-require": 0,
      "grouped-accessor-pairs": 2,
      "guard-for-in": 0,
      "handle-callback-err": 2,
      "id-blacklist": 2,
      "id-denylist": 2,
      "id-length": 0,
      "id-match": 2,
      "implicit-arrow-linebreak": 0,
      indent: 0,
      "indent-legacy": 0,
      "init-declarations": 2,
      "jsx-quotes": 2,

      "key-spacing": [
        2,
        {
          beforeColon: false,
          afterColon: true,
        },
      ],

      "keyword-spacing": 2,
      "linebreak-style": [0, "windows"],
      "line-comment-position": 0,
      "lines-around-comment": 2,
      "lines-around-directive": 2,
      "lines-between-class-members": 2,
      "max-classes-per-file": 2,
      "max-depth": [0, 4],
      "max-len": [0, 80, 4],
      "max-lines": 0,
      "max-lines-per-function": 0,
      "max-nested-callbacks": [0, 2],
      "max-params": [0, 3],
      "max-statements": [0, 10],
      "max-statements-per-line": 2,
      "multiline-comment-style": 0,
      "multiline-ternary": 0,
      "new-cap": 0,
      "newline-after-var": 0,
      "newline-before-return": 0,
      "newline-per-chained-call": 0,
      "new-parens": 2,
      "no-alert": 2,
      "no-array-constructor": 2,
      "no-async-promise-executor": 2,
      "no-await-in-loop": 2,
      "no-bitwise": 0,
      "no-buffer-constructor": 2,
      "no-caller": 2,
      "no-case-declarations": 2,
      "no-catch-shadow": 2,
      "no-class-assign": 2,
      "no-compare-neg-zero": 2,
      "no-cond-assign": 2,
      "no-confusing-arrow": 0,
      "no-console": 2,
      "no-constant-binary-expression": 2,
      "no-constant-condition": 2,
      "no-const-assign": 2,
      "no-constructor-return": 2,
      "no-continue": 0,
      "no-control-regex": 0,
      "no-debugger": 2,
      "no-delete-var": 2,
      "no-div-regex": 2,
      "no-dupe-args": 2,
      "no-dupe-class-members": 2,
      "no-dupe-else-if": 2,
      "no-dupe-keys": 2,
      "no-duplicate-case": 2,
      "no-duplicate-imports": 2,
      "no-else-return": 2,
      "no-empty": 2,
      "no-empty-character-class": 2,
      "no-empty-function": 2,
      "no-empty-pattern": 2,
      "no-eq-null": 2,
      "no-eval": 2,
      "no-ex-assign": 2,
      "no-extend-native": 2,
      "no-extra-bind": 2,
      "no-extra-boolean-cast": 2,
      "no-extra-label": 2,
      "no-extra-parens": 0,
      "no-extra-semi": 2,
      "no-fallthrough": 2,
      "no-floating-decimal": 2,
      "no-func-assign": 2,
      "no-global-assign": 2,
      "no-implicit-coercion": 2,
      "no-implicit-globals": 2,
      "no-implied-eval": 2,
      "no-import-assign": 2,
      "no-inline-comments": 0,
      "no-inner-declarations": [2, "functions"],
      "no-invalid-regexp": 2,
      "no-invalid-this": 2,
      "no-irregular-whitespace": 2,
      "no-iterator": 2,
      "no-labels": 2,
      "no-label-var": 2,
      "no-lone-blocks": 2,
      "no-lonely-if": 2,
      "no-loop-func": 0,
      "no-loss-of-precision": 2,
      "no-magic-numbers": 0,
      "no-misleading-character-class": 0,
      "no-mixed-operators": 0,
      "no-mixed-requires": [2, false],
      "no-mixed-spaces-and-tabs": [2, false],
      "no-multi-assign": 2,

      "no-multiple-empty-lines": [
        2,
        {
          max: 2,
        },
      ],

      "no-multi-spaces": 2,
      "no-multi-str": 2,
      "no-native-reassign": 2,
      "no-negated-condition": 2,
      "no-negated-in-lhs": 2,
      "no-nested-ternary": 2,
      "no-new": 2,
      "no-new-func": 2,
      "no-new-object": 2,
      "no-new-require": 2,
      "no-new-symbol": 2,
      "no-new-wrappers": 2,
      "no-nonoctal-decimal-escape": 2,
      "no-obj-calls": 2,
      "no-octal": 2,
      "no-octal-escape": 2,
      "no-param-reassign": 2,
      "no-path-concat": 2,
      "no-plusplus": 0,
      "no-process-env": 0,
      "no-process-exit": 2,
      "no-promise-executor-return": 2,
      "no-proto": 2,
      "no-prototype-builtins": 2,
      "no-redeclare": 2,
      "no-regex-spaces": 2,
      "no-restricted-exports": 2,
      "no-restricted-globals": 2,
      "no-restricted-imports": 2,
      "no-restricted-modules": 2,
      "no-restricted-properties": 2,
      "no-restricted-syntax": 2,
      "no-return-assign": 2,
      "no-return-await": 2,
      "no-script-url": 2,
      "no-self-assign": 2,
      "no-self-compare": 2,
      "no-sequences": 2,
      "no-setter-return": 2,
      "no-shadow": 2,
      "no-shadow-restricted-names": 2,
      "no-spaced-func": 2,
      "no-sparse-arrays": 2,
      "no-sync": 2,
      "no-tabs": 2,
      "no-template-curly-in-string": 2,
      "no-ternary": 0,
      "no-this-before-super": 2,
      "no-throw-literal": 2,
      "no-trailing-spaces": 2,
      "no-undef": 2,
      "no-undefined": 0,
      "no-undef-init": 2,
      "no-underscore-dangle": 2,
      "no-unexpected-multiline": 2,
      "no-unmodified-loop-condition": 2,
      "no-unneeded-ternary": 2,
      "no-unreachable": 2,
      "no-unreachable-loop": 2,
      "no-unsafe-finally": 2,
      "no-unsafe-negation": 2,
      "no-unsafe-optional-chaining": 2,
      "no-unused-expressions": 2,
      "no-unused-labels": 2,
      "no-unused-private-class-members": 2,

      "no-unused-vars": [
        2,
        {
          vars: "all",
          args: "after-used",
        },
      ],

      "no-use-before-define": 0,
      "no-useless-backreference": 2,
      "no-useless-call": 2,
      "no-useless-catch": 2,
      "no-useless-computed-key": 2,
      "no-useless-concat": 2,
      "no-useless-constructor": 2,
      "no-useless-escape": 2,
      "no-useless-rename": 2,
      "no-useless-return": 2,
      "no-var": 2,
      "no-void": 2,

      "no-warning-comments": [
        1,
        {
          terms: ["todo", "fixme", "xxx"],
          location: "start",
        },
      ],

      "no-whitespace-before-property": 2,
      "no-with": 2,
      "object-curly-newline": 2,
      "object-curly-spacing": [0, "never"],
      "object-property-newline": 0,
      "object-shorthand": 2,
      "one-var": 0,
      "one-var-declaration-per-line": 2,
      "operator-assignment": [0, "always"],
      "operator-linebreak": [0, "after"],
      "padded-blocks": 0,
      "padding-line-between-statements": 2,
      "prefer-arrow-callback": 2,
      "prefer-const": 2,
      "prefer-destructuring": 0,
      "prefer-exponentiation-operator": 0,
      "prefer-named-capture-group": 0,
      "prefer-numeric-literals": 2,
      "prefer-object-has-own": 2,
      "prefer-object-spread": 2,
      "prefer-promise-reject-errors": 2,
      "prefer-reflect": 2,
      "prefer-regex-literals": 2,
      "prefer-rest-params": 2,
      "prefer-spread": 2,
      "prefer-template": 2,
      "quote-props": 0,
      quotes: [2, "double"],
      radix: 2,
      "require-atomic-updates": 2,
      "require-await": 0,
      "require-jsdoc": 0,
      "require-unicode-regexp": 2,
      "require-yield": 2,
      "rest-spread-spacing": 2,
      semi: [2, "always"],

      "semi-spacing": [
        0,
        {
          before: false,
          after: true,
        },
      ],

      "semi-style": 2,
      "sort-imports": 0,
      "sort-keys": 0,
      "sort-vars": 0,
      "space-after-keywords": [0, "always"],
      "space-before-blocks": [0, "always"],
      "space-before-function-paren": [0, "always"],
      "spaced-comment": 0,
      "space-infix-ops": 2,
      "space-in-parens": [2, "never"],

      "space-unary-ops": [
        0,
        {
          words: true,
          nonwords: false,
        },
      ],

      strict: 2,
      "switch-colon-spacing": 2,
      "symbol-description": 2,
      "template-curly-spacing": 2,
      "template-tag-spacing": 2,
      "@typescript-eslint/no-explicit-any": 0,
      "@typescript-eslint/no-require-imports": 0,
      "unicode-bom": 2,
      "use-isnan": 2,
      "valid-typeof": 2,
      "vars-on-top": 2,
      "wrap-iife": [2, "inside"],
      "wrap-regex": 2,
      "yield-star-spacing": 2,
      yoda: [2, "never"],
    },
  },
]);

export default eslintConfig;
